### ISSUE TITLE
How to use Alt in Whisky?

### ISSUE THREAD

**Issue by tyIceStream** [IsaacMarovitz/Whisky#214]
Hi, I want to use Alt when I run exe via Whisky.
I find that the "Option" in Mac does not map to "Alt" in Windows, and don't know how to set this?
Any solution for this?

**Comment by IsaacMarovitz** [comment]
Is this issue a problem with a specific game or something? Usually, options will map to alt within Wine.

**Comment by tyIceStream** [comment]
I run Genshin Impact via Whisky. I don't know if this issue occurs on another application.
Maybe it's just for me because I use MacOS 13 instead of 14

**Comment by IsaacMarovitz** [comment]
> I run Genshin Impact via Whisky. I don't know if this issue occurs on another application. Maybe it's just for me because I use MacOS 13 instead of 14

Which part of Genshin requires you to press Alt? Also, you can easily change key binds in the game's settings.

**Comment by wilt00** [comment]
I think that this issue should be reopened.

I used [this program](https://www.passmark.com/products/keytest/index.php) to test which keys are passed through to Whiskey, and no keys map to Alt, Win, or F11. In the screenshot below, I'm starting to press the macOS keyboard shortcut `Cmd + Shift + 4 + Space` to screenshot the window; despite pressing Cmd before Shift, you can see that only Shift shows as being pressed.
<img width="1144" alt="Screenshot 2023-08-16 at 11 46 34 PM" src="https://github.com/IsaacMarovitz/Whisky/assets/7883508/e2bf179a-e8e7-49d6-bc54-f7e81285e7d4">
Also, using notepad.exe to test, in Windows `Alt+2` should type ☻ (smiley face), but it instead types ™ (trademark), which is `Opt+2` on macOS.

According to the upstream bug report [here](https://bugs.winehq.org/show_bug.cgi?id=35351), the intended behavior is that Command map to Alt, and Option map to nothing. The reason given for this is that in some international keyboard layouts, Alt codes are required to type important characters (e.g. @ for the French keyboard layout), making this a much more serious issue than just a game key mapping bug. (Incidentally, per the poster's original report, Esc and Left Alt are the only two keys that cannot be rebound in Genshin Impact.) I tested the registry keys at that link; RightCommandIsCtrl does remap right Cmd to right Ctrl, but LeftOptionIsAlt does not remap left option to left alt.

Setting the [Scancode Map](https://learn.microsoft.com/en-us/windows-hardware/drivers/hid/keyboard-and-mouse-class-drivers#scan-code-mapper-for-keyboards) registry key does not seem to have any effect for any keys. Global macOS Karabiner-elements key remappings do apply to Wine, but Opt/Alt is still not sent. I have no other ideas short of [recompiling Wine](https://palant.info/2014/02/14/crazy-hacks-changing-wine-key-mappings-on-mac-os-x/) which I might try this weekend if I have time, but since the author of that blog post is the same person who submitted the previously linked bugzilla report, I'm not super optimistic.

**Comment by ojsef39** [comment]
Why was this closed? This issue is still there, i have Steam Overlay on Alt+S and neither Alt nor Control are working.
